(in-package :erudite)

(defvar *short-comments-prefix* ";;")
(defvar *syntax* :erudite)
(defvar *output-type* :latex)
(defvar *title* nil)
(defvar *subtitle* nil)
(defvar *author* nil)
(defvar *current-path* nil)
(defvar *chunks* nil)
(defvar *catch-errors-p* t)
(defvar *verbose* nil)
(defvar *debug* nil)

(log:config :off)
