(in-package :erudite)

(defvar *short-comments-prefix* ";;")
(defvar *syntax* :erudite)
(defvar *output-type* :latex)
(defvar *title* nil)
(defvar *subtitle* nil)
(defvar *author* nil)
(defvar *current-path* nil)
(defvar *chunks* nil)
(defvar *catch-errors-p* t)
(defvar *verbose* nil)
(defvar *debug* nil)
(defvar *code-indexing* t)
(defvar *erudite-package* (find-package :erudite))
(defvar *implicit-doc* t)
(defvar *implicit-code* t)

(log:config :off)
